import Foundation

/// Writes the initial Abbot configuration files (~/.abbot/abbot.toml and ~/.abbot/keys.env).
struct ConfigWriter {
    struct SetupConfig {
        let provider: String
        let apiKey: String
        let model: String
    }

    static let abbotDir: URL = {
        FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".abbot")
    }()

    static let configPath: URL = {
        abbotDir.appendingPathComponent("abbot.toml")
    }()

    static let keysPath: URL = {
        abbotDir.appendingPathComponent("keys.env")
    }()

    static var configExists: Bool {
        FileManager.default.fileExists(atPath: configPath.path)
    }

    /// Provider metadata: (id, display name, base URL, api_key_env name, default model).
    static let providers: [(id: String, name: String, baseURL: String, keyEnv: String, defaultModel: String)] = [
        ("anthropic", "Anthropic", "https://api.anthropic.com/v1", "ANTHROPIC_API_KEY", "claude-sonnet-4-5-20250929"),
        ("openai", "OpenAI", "https://api.openai.com/v1", "OPENAI_API_KEY", "gpt-4o"),
        ("gemini", "Gemini", "https://generativelanguage.googleapis.com/v1beta/openai", "GEMINI_API_KEY", "gemini-2.0-flash"),
        ("xai", "X.ai", "https://api.x.ai/v1", "XAI_API_KEY", "grok-3-mini-fast-beta"),
        ("zai", "Z.ai", "https://api.z.ai/api/paas/v4", "ZAI_API_KEY", "deepseek-chat"),
        ("openrouter", "OpenRouter", "https://openrouter.ai/api/v1", "OPENROUTER_API_KEY", "anthropic/claude-sonnet-4-5"),
        ("ollama", "Ollama (Local)", "http://localhost:11434/v1", "", "llama3.1"),
    ]

    /// Trait categories with "none" as default for all.
    private static let traitCategories = [
        "fever", "generation", "autist", "filter", "poverty", "ego",
        "paranoia", "cultist", "dominance", "bipolar", "xenophobe",
        "esoteric", "collab",
    ]

    static func write(config: SetupConfig) throws {
        // Create ~/.abbot/ if needed
        try FileManager.default.createDirectory(at: abbotDir, withIntermediateDirectories: true)

        // Write keys.env
        let provider = providers.first { $0.id == config.provider }
        if let provider = provider, !provider.keyEnv.isEmpty, !config.apiKey.isEmpty {
            let keysContent = "\(provider.keyEnv)=\(config.apiKey)\n"
            try keysContent.write(to: keysPath, atomically: true, encoding: .utf8)
            // Restrict permissions to owner-only
            try FileManager.default.setAttributes(
                [.posixPermissions: 0o600],
                ofItemAtPath: keysPath.path
            )
        }

        // Build traits section (all "none" by default)
        let traitsSection = traitCategories.map { "\($0) = \"none\"" }.joined(separator: "\n")

        // Build all provider sections
        let providerSections = providers.map { p in
            """
            [providers.\(p.id)]
            base_url = "\(p.baseURL)"
            api_key_env = "\(p.keyEnv)"
            """
        }.joined(separator: "\n\n")

        let toml = """
        # Abbot configuration (generated by Abbot.app)
        developer = false

        [server]
        addr = "127.0.0.1:8080"
        log_format = "default"
        # proxy_base_url = ""
        # web_dist = ""
        allow_loopback_main_scope = false
        allow_cors_any = false

        \(providerSections)

        [llm]
        model = "\(config.model)"
        temperature = 0.7
        # max_tokens = 4096

        [traits]
        \(traitsSection)

        [head]
        heartbeat_tick = 30
        debounce_ms = 500

        [hand]
        max_iters = 24

        [mind]
        tick_interval = 1800

        [prompt_cache]
        # enabled = false

        [harness]
        # model = ""

        # [vfs]
        # mounts = []
        """

        try toml.write(to: configPath, atomically: true, encoding: .utf8)
    }
}
