#!/usr/bin/env bash
#
# first-run.sh — Simulate a user's first run after installing abbot.
#
# Uses a temporary HOME so that ~/.abbot/ is created from scratch.
# Since `abbot init` is interactive, this script writes the config
# directly via heredoc (using ollama/llama3.2 which needs no API key),
# then starts the daemon.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

echo "==> Building abbot workspace..."
cargo build --manifest-path "$SCRIPT_DIR/Cargo.toml" 2>&1 | tail -5

ABBOTD="$SCRIPT_DIR/target/debug/abbotd"
ABBOT="$SCRIPT_DIR/target/debug/abbot"

if [[ ! -x "$ABBOTD" ]] || [[ ! -x "$ABBOT" ]]; then
    echo "ERROR: binaries not found after build"
    exit 1
fi

# ---------------------------------------------------------------------------
# Prepare isolated HOME
# ---------------------------------------------------------------------------

FAKE_HOME="$(mktemp -d /tmp/abbot-first-run.XXXXXX)"
export HOME="$FAKE_HOME"

cleanup() {
    echo
    echo "==> Cleaning up $FAKE_HOME"
    rm -rf "$FAKE_HOME"
}
trap cleanup EXIT

echo "==> Using temporary HOME=$FAKE_HOME"
echo

# ---------------------------------------------------------------------------
# Step 1: Verify nothing exists yet
# ---------------------------------------------------------------------------

echo "--- Step 1: Verify clean slate ---"
if [[ -d "$FAKE_HOME/.abbot" ]]; then
    echo "FAIL: .abbot already exists before first run"
    exit 1
fi
echo "OK: no .abbot directory yet"
echo

# ---------------------------------------------------------------------------
# Step 2: Verify daemon refuses to start without config
# ---------------------------------------------------------------------------

echo "--- Step 2: Verify daemon refuses without config ---"
set +e
"$ABBOTD" --exit --log-format compact run prompt "hello" 2>&1
DAEMON_EXIT=$?
set -e

if [[ $DAEMON_EXIT -ne 0 ]]; then
    echo "OK: daemon refused to start without config (exit code $DAEMON_EXIT)"
else
    echo "FAIL: daemon should have refused to start without config"
    exit 1
fi
echo

# ---------------------------------------------------------------------------
# Step 3: Write config via heredoc (simulating `abbot init`)
# ---------------------------------------------------------------------------

echo "--- Step 3: Write config (simulating abbot init) ---"
mkdir -p "$FAKE_HOME/.abbot"
cat > "$FAKE_HOME/.abbot/abbot.toml" <<'EOF'
# Abbot configuration
# Generated by first-run.sh (simulating abbot init)

[server]
addr = "127.0.0.1:8080"
log_format = "default"
allow_loopback_main_scope = false
allow_cors_any = false

[providers.openrouter]
base_url = "https://openrouter.ai/api/v1"
api_key_env = "OPENROUTER_API_KEY"

[providers.anthropic]
base_url = "https://api.anthropic.com/v1"
api_key_env = "ANTHROPIC_API_KEY"

[providers.openai]
base_url = "https://api.openai.com/v1"
api_key_env = "OPENAI_API_KEY"

[providers.ollama]
base_url = "http://localhost:11434/v1"
api_key_env = ""

[head]
model = "ollama/llama3.2"
temperature = 0.7
heartbeat_tick = 30
debounce_ms = 500

[hand]
model = "ollama/llama3.2"
temperature = 0.3
max_iters = 24

[mind]
model = "ollama/llama3.2"
tick_interval = 60
EOF
echo "OK: wrote $FAKE_HOME/.abbot/abbot.toml"
echo

# ---------------------------------------------------------------------------
# Step 4: Start the daemon (with config present)
# ---------------------------------------------------------------------------

echo "--- Step 4: Start daemon (with config) ---"

# We expect preflight to fail (no Ollama running in CI),
# so we accept exit code != 0 here.
set +e
"$ABBOTD" --exit --log-format compact run prompt "hello" 2>&1
DAEMON_EXIT=$?
set -e

if [[ $DAEMON_EXIT -eq 0 ]]; then
    echo "OK: daemon exited cleanly"
else
    echo "OK: daemon exited with code $DAEMON_EXIT (expected if no Ollama)"
fi
echo

# ---------------------------------------------------------------------------
# Step 5: Verify generated files
# ---------------------------------------------------------------------------

echo "--- Step 5: Verify generated files ---"
PASS=true

check_exists() {
    local label="$1" path="$2"
    if [[ -e "$path" ]]; then
        echo "  [x] $label: $path"
    else
        echo "  [ ] $label: $path  (MISSING)"
        PASS=false
    fi
}

check_exists "config file" "$FAKE_HOME/.abbot/abbot.toml"
check_exists "data dir"    "$FAKE_HOME/.abbot"
check_exists "mind dir"    "$FAKE_HOME/.abbot/mind"

echo
if $PASS; then
    echo "OK: all expected files present"
else
    echo "WARN: some files missing (may be expected if daemon failed early)"
fi
echo

# ---------------------------------------------------------------------------
# Step 6: Read the generated config
# ---------------------------------------------------------------------------

echo "--- Step 6: Read generated config ---"
if [[ -f "$FAKE_HOME/.abbot/abbot.toml" ]]; then
    "$ABBOT" config get 2>&1 || true
else
    echo "(skipped — config not generated)"
fi
echo

# ---------------------------------------------------------------------------
# Step 7: Test config set/get roundtrip
# ---------------------------------------------------------------------------

echo "--- Step 7: Config set/get roundtrip ---"
if [[ -f "$FAKE_HOME/.abbot/abbot.toml" ]]; then
    echo "Setting head.temperature=0.42..."
    "$ABBOT" config set head temperature=0.42 2>&1 || true
    echo
    echo "Reading back [head] section:"
    "$ABBOT" config get head 2>&1 || true
else
    echo "(skipped — config not generated)"
fi
echo

# ---------------------------------------------------------------------------
# Step 8: Show system info
# ---------------------------------------------------------------------------

echo "--- Step 8: System info ---"
"$ABBOT" info 2>&1 || true
echo

# ---------------------------------------------------------------------------
# Step 9: Check preflight log
# ---------------------------------------------------------------------------

echo "--- Step 9: Preflight log ---"
if [[ -f "$FAKE_HOME/.abbot/preflight.log" ]]; then
    cat "$FAKE_HOME/.abbot/preflight.log"
else
    echo "(no preflight.log — daemon may have exited before writing it)"
fi
echo

# ---------------------------------------------------------------------------
# Step 10: Show directory listing
# ---------------------------------------------------------------------------

echo "--- Step 10: Final directory layout ---"
find "$FAKE_HOME/.abbot" -type f -o -type d | sort | while read -r f; do
    rel="${f#$FAKE_HOME/}"
    if [[ -d "$f" ]]; then
        echo "  $rel/"
    else
        size=$(wc -c < "$f" 2>/dev/null || echo "?")
        echo "  $rel  ($size bytes)"
    fi
done
echo

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo "==> First-run simulation complete."
