//! Patch Namespace - Unified diff patch application with workspace isolation
//!
//! ARCHITECTURE OVERVIEW
//! =====================
//! This namespace provides controlled application of unified diff patches within the
//! Abbot kernel's security model. It enables programmatic file modification via the
//! standard diff/patch workflow while enforcing VFS-based workspace boundaries.
//!
//! **Registered syscalls:**
//! - `patch:apply` - Apply unified diff patches with VFS path validation
//!
//! **Integration points:**
//! - VFS layer for path security validation
//! - HAL process abstraction for `patch` utility execution
//! - Actor model for mutation permission enforcement
//!
//! DESIGN PHILOSOPHY
//! =================
//! - **Standard tooling**: Delegate to battle-tested `patch` utility rather than
//!   reimplementing diff parsing and application logic
//! - **VFS-first security**: All filesystem paths validated through VFS layer before
//!   execution (prevents workspace escapes)
//! - **Fail-fast validation**: Parse and validate all diff headers before invoking
//!   `patch` utility to provide clear error messages
//! - **Mutation guard**: Only "head" agents may apply patches (prevents unauthorized
//!   file modification from LLM-controlled "hand" agents)
//! - **Stdin-based execution**: Pipe patch content directly to utility (prevents
//!   temporary file race conditions)
//!
//! SECURITY MODEL
//! ==============
//! The patch namespace implements defense-in-depth for file mutation:
//!
//! 1. **Actor Authorization**
//!    - WHY: Patch application modifies files, so restricted to "head" agents
//!    - PREVENTS: Compromised LLMs from applying malicious patches
//!
//! 2. **VFS Path Validation**
//!    - WHY: Ensures all patch targets are within mounted workspaces
//!    - PREVENTS: Path traversal (`../../etc/passwd`), absolute path escapes (`/etc/passwd`)
//!    - MECHANISM: Parse `---` and `+++` headers, validate each path via VFS before execution
//!
//! 3. **Format Validation**
//!    - WHY: Prevents execution of arbitrary content disguised as patches
//!    - MECHANISM: Require presence of unified diff headers (`---`, `+++`)
//!
//! 4. **Output Limiting**
//!    - WHY: Prevents memory exhaustion from verbose patch output
//!    - MECHANISM: 256KB stdout/stderr limits, 4000 character response truncation
//!
//! USE CASES
//! =========
//! - Applying code changes generated by LLMs or code analysis tools
//! - Integrating with external version control workflows (e.g., applying GitHub PR diffs)
//! - Programmatic file modification via standard diff format (interoperable with git, diff, etc.)
//!
//! TRADE-OFFS
//! ==========
//! 1. **External Dependency**
//!    - CHOSEN: Delegate to system `patch` utility (not pure Rust implementation)
//!    - WHY: `patch` utility is battle-tested, handles edge cases (fuzzy matching, conflicts)
//!    - IMPLICATION: Requires `patch` binary in PATH (standard on Unix systems)
//!
//! 2. **No Dry-Run Mode**
//!    - CHOSEN: Apply patches immediately (no `--dry-run` pre-validation)
//!    - WHY: Simpler implementation, consistent with git workflow (patches can fail)
//!    - MITIGATION: Git version control allows reverting failed patches
//!
//! 3. **Path Validation Overhead**
//!    - CHOSEN: Parse and validate all diff headers before execution
//!    - WHY: Fail-fast with clear error messages for workspace boundary violations
//!    - COST: Double-parsing overhead (once here, once by `patch` utility)
//!    - ACCEPTABLE: Patches are typically small, parsing cost is negligible

mod apply;

pub use apply::PatchApply;

use crate::kernel::KernelDispatcher;
use std::sync::Arc;

/// Register all patch syscalls with the kernel dispatcher.
///
/// WHY: Centralized registration ensures all patch operations are available
/// when the kernel starts. Called during kernel initialization.
pub fn register(dispatcher: &mut KernelDispatcher) {
    dispatcher.register(Arc::new(PatchApply::new()));
}
